export const FETCH_MOVIE_INITIATED = "FETCH_MOVIE_INITIATED";
export const FETCH_MOVIE_FAILED = "FETCH_MOVIE_FAILED";
export const FETCH_MOVIE_SUCCEEDED = "FETCH_MOVIE_SUCCEEDED";

export const FETCH_MOVIES_INITIATED = "FETCH_MOVIES_INITIATED";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FETCH_MOVIES_SUCCEEDED = "FETCH_MOVIES_SUCCEEDED";

export const FETCH_TRAILERS_INITIATED = "FETCH_TRAILERS_INITIATED";
export const FETCH_TRAILERS_FAILED = "FETCH_TRAILERS_FAILED";
export const FETCH_TRAILERS_SUCCEEDED = "FETCH_TRAILERS_SUCCEEDED";
export const SEARCH_QUERY_SUBMITTED = "SEARCH_QUERY_SUBMITTED";

export const FETCH_TRAILERS = "FETCH_TRAILERS";

export const ADDED_FAVORITE = "ADDED_FAVORITE";
export const REMOVED_FAVORITE = "REMOVED_FAVORITE";
export const REMOVEMODE_TOGGLED = "REMOVEMODE_TOGGLED";

export const VIDEO_CLICKED = "VIDEO_CLICKED";
export const MOVIE_CLICKED = "MOVIE_CLICKED";
