export const FETCH_MOVIE = "FETCH_MOVIE";

export const FETCH_MOVIES_INITIATED = "FETCH_MOVIES_INITIATED";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FETCH_MOVIES_SUCCEEDED = "FETCH_MOVIES_SUCCEEDED";

export const ADDED_FAVORITE = "ADDED_FAVORITE";
export const REMOVED_FAVORITE = "REMOVED_FAVORITE";

export const MOVIE_CLICKED = "MOVIE_CLICKED";
